name: CMake-Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
      CMAKE_BUILD_OPTIONS: -DBUILD_TESTS=ON -DBUILD_PROFILER=ON
      BUILD_DIR: ${{github.workspace}}/cmake-build-release/

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} ${{env.CMAKE_BUILD_OPTIONS}}

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}}

      - name: Upload build artifacts for tests
        env:
          TESTS_DIR: ${{github.workspace}}/treelib/cmake-build-release/
        uses: actions/upload-artifacts@v2
        with:
          name: artifacts-for-tests
          path: ${{env.TESTS_DIR}}/

      - name: Upload build artifacts for profiler
        env:
          PROFILER_DIR: ${{env.BUILD_DIR}}/profiler/
        uses: actions/upload-artifacts@v2
        with:
          name: artifacts-for-profiler
          path: ${{env.PROFILER_DIR}}/run_profiler

  Tests:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Download artifacts for tests
        uses: actions/download-artifact@v2
        with:
          name: artifacts-for-tests

      - name: ls
        run: |
          ls -la

  Profiling:
    runs-on: ubuntu-latest
    needs: Tests
    
    steps:
      - name: Download artifacts for profiler
        uses: actions/download-artifact@v2
        with:
          name: artifacts-for-profiler

      - name: ls
        run: |
          ls -la